gkoh/furble

lib/furble/CanonEOSM6.cpp
lib/furble/FujifilmXT30.cpp
lib/furble/Furble.h
src/furble.ino

Modify the shutter menu, now:
A: Trigger shutter
B: Hold until focus
PWR: Back
Sending '0x03' on the shutter characteristic (for Fujifilm) appears to activate a partial shutter press, thus simulating the physical 'partial press to focus'.
Canon EOS M6 is unsupported for now, need to regain access to test.

Support focus command.

---

lib/furble/CanonEOSRP.cpp
lib/furble/Device.cpp
lib/furble/Furble.h

BLE GATTR service guids looks the same as for M6
This works, but throws "Connection target not found" on camera, when connection to "furble" is not speedily confirmed.
How-to:
- on camera Wireless communication settings -> Bluetooth function -> Smartphone
- start Pairing, select "Do not display" (Android/Iphone connecting info)
- camera will show Pairing in progress
- start scan on M5Stick
- one camera will be found
- click to Connect
- on Camera you will be prompted for 5 seconds to confirm connecting to smartphone "furble" - click OK
- if you were successfull, camera shows "Paired with: furble"

initial EOSRP support

---

lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/CanonEOSRP.cpp
lib/furble/Fujifilm.cpp

We now wait for 60s for the user to accept/reject the pairing.
Whilst here, disable the focus button so it doesn't do the unexpected.

Add indication handling for the pairing accept/deny for Canon EOS.

---

lib/furble/Fujifilm.cpp

Looks like some odd interaction between the new firmware and NimBLE-Arduino library.
Adding a required response ensured the connection could be paired and completed.

Fix pairing with new libraries and firmware.

---

lib/M5ez/src/M5ez.cpp
lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/Device.h
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h
platformio.ini
src/furble.ino
src/settings.ino

Add support for the Grove GPS unit.

43 add gps location and time sync support

---

src/furble.ino

The latency for BLE comms can easily exceed any human click speed. If this happens, we lose button events.
Handle this by forcing an M5.Update() immediately after sending a command to the camera.
Whilst here:
- change the loop semantic (coz I can)
- handle the shutter control back button without conditional compilation
- let the M5Unified library work out if the buttons actually exist

Handle humans spamming shutter or focus buttons.

---

lib/M5ez/src/M5ez.cpp

Lower the battery level max so 4 bars is 85-100%.
Otherwise, anything less than 100% is 3 bars.

Fix high charge battery level mapping.

---

.github/workflows/release.yml
web-installer/generate-manifest.py
web-installer/index.html
web-installer/manifest.tmpl

Using esp-web-tools we can now flash an ESP32 from a supported browser.
To support this properly:
* add the 4 binary image artifacts required to fully flash an ESP32
* add an esp-web-tools manifest generator and workflow step
* add an index page to drive esp-web-tools
* add a release step to gather and deploy _all_ the pieces automatically
On next major release (v2.0.0), a website will be deployed, the final URL will be announced at that time.

Add support for web based installation.

---

lib/M5ez/src/M5ez.cpp
lib/M5ez/src/M5ez.h
lib/furble/Device.cpp
lib/furble/Device.h
lib/furble/Fujifilm.cpp
src/furble.ino

Monitors the Bluetooth connection status for the device and attempts an automatic reconnect whenever the connection drops
Some changes requires to M5ez to add functionality to get the current buttons
Device class is also updated to support querying connection status

Add bluetooth connection disconnect handling

---

lib/furble/Camera.cpp
lib/furble/Camera.h
lib/furble/Furble.cpp
lib/furble/Furble.h
src/furble.cpp

As per the ESP32 docs, set the BLE power _after_ we have established the connection.
Whilst here, refactor the handling so 'Scan::init()' sets the power before setup and 'Camera::connect()' sets the power after success.

Set BLE power after connection is established.

---

lib/furble/Camera.cpp
lib/furble/Camera.h
lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/CanonEOSM6.cpp
lib/furble/CanonEOSM6.h
lib/furble/CanonEOSRP.cpp
lib/furble/CanonEOSRP.h
lib/furble/Device.cpp
lib/furble/Device.h
lib/furble/Fujifilm.cpp
lib/furble/Furble.cpp
src/furble.cpp

Minor C++ refactor.
Use static_cast where possible.
Migrate to class function binding rather than static.
Default to parent class constructor using initialisers.
Add unique ID to connection parameter.
When connecting, append a subset of the ESP32 'unique' identifier, which
is derived from the device MAC address.

Add unique ID to connection parameter.

---

README.md
lib/furble/CameraList.cpp
lib/furble/CameraList.h
src/furble.cpp

Disable 'Connect' and 'Delete Saved' if there are no connections.
Also, fix a bug with deleting down to zero connections by removing the
preference entry.

85 disable connect and delete saved if there are no connections

---

.github/workflows/release.yml

pages-action will be deprecated, migrate to the replacement wrangler-action.
Change release trigger to the publish event.
Bump action-gh-release to v2.

Migrate from pages-action to wrangler-action for release deployment.

---

lib/furble/CameraList.cpp
lib/furble/CanonEOS.cpp
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h
src/furble.cpp
src/interval.cpp
src/settings.cpp

Use the 128-bit UUID for geotag characteristic.
The 16-bit handle is not consistent across devices or firmware versions.

Fix GPS geotag support for different firmware versions.

---

README.md

Try to better document what features work and where.
Also, add missing intervalometer feature.
Fix #105

Add table of features to README

---

lib/M5ez/src/M5ez.cpp
lib/M5ez/src/M5ez.h

I made the lowest brightness of the backlight change depending on the device, and also modified the brightness slider to have 8 levels.
#111 Backlight timeout brightness is hardcoded and too high and #112 Backlight menu slider needs tweaking.
The name of the board is referenced here.( https://docs.m5stack.com/en/arduino/m5unified/m5unified_appendix )

111, 112 Backlight handling improve

---

src/furble.cpp

Absorb the geotag updates into the disconnect detection event. Now, as long as we are connected to the camera, we can provide GPS updates.

Update geotag data whilst connected.

---

lib/furble/Camera.cpp
lib/furble/Camera.h

Increase the latency to 1 (from default 0).
Double the supervision timeout (so disconnection isn't as sensitive).

Adjust connection parameters to increase communication range.

---

include/furble_control.h
include/furble_gps.h
include/furble_ui.h
lib/M5ez/src/M5ez.cpp
lib/furble/Camera.cpp
lib/furble/Camera.h
src/furble.cpp
src/furble_control.cpp
src/furble_gps.cpp
src/interval.cpp
src/main.cpp
src/spinner.cpp

Still using the Arduino framework, however we now use the underlying FreeRTOS for better control over tasks.
Initially, split the UI and control to separate tasks, furthermore, use a queue to manage camera control.
This almost allows the UI to operate without constraints on camera traffic.

Migrate to FreeRTOS for UI and camera control.

---

include/settings.h
include/spinner.h
lib/furble/Camera.cpp
lib/furble/Camera.h
lib/furble/CameraList.cpp
lib/furble/CameraList.h
lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/CanonEOSM6.cpp
lib/furble/CanonEOSM6.h
lib/furble/CanonEOSRP.cpp
lib/furble/CanonEOSRP.h
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h
lib/furble/HIDServer.cpp
lib/furble/HIDServer.h
lib/furble/MobileDevice.cpp
lib/furble/MobileDevice.h
platformio.ini
src/furble.cpp
src/interval.cpp
src/settings.cpp
src/spinner.cpp

Strengthen immutability by adding more const qualifiers.
Use some more iterators.
Reduce binary size further by disabling exceptions.

Curate more C++ features.

---

README.md
lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h

Remove unneeded WiFi handshake.
Clarify GPS only works over WiFi for this model.

Minor cleanup of Canon EOS M6.

---

lib/furble/Furble.cpp

This may (or may not) help debug signal strength issues.

Log RSSI from scan matches.

---

README.md
platformio.ini

This is extra weird, disabling exceptions via compiler flags breaks new pairing with Fujifilm cameras.
I don't understand, re-enable for now.

Re-enable exceptions.

---

README.md
include/furble_control.h
include/furble_ui.h
include/settings.h
lib/M5ez/src/M5ez.cpp
lib/M5ez/src/M5ez.h
lib/furble/Camera.cpp
lib/furble/Camera.h
lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h
lib/furble/MobileDevice.cpp
lib/furble/MobileDevice.h
src/furble.cpp
src/furble_control.cpp
src/interval.cpp
src/settings.cpp

Enable a user to cancel a connection attempt.
Merge in #132 from @hijae for the settings to control the behaviour.
With this change, the following will occur:
* with `Infinite-ReConnect = OFF` 
* `furble` will attempt a single reconnect on connection drop
* a successful reconnect will reset the counter
* with `Infinite-ReConnect = ON`
*  `furble` will attempt to reconnect indefinitely, unless `Cancel` is pressed
* M5ez menu handling doesn't help us here, the control menu will be shown, but any item press will exit

Implement infinite reconnect and cancel.

---

src/FurbleUI.cpp

On M5StickC the version text was clipped.
Fix by adding a new line as needed.

Adjust 'About' text width.

---

include/FurbleControl.h
src/FurbleControl.cpp

It was possible for the Target object to be destructed before it stopped.
This manifested as a crash when freed memory was accessed. Add a flag to wait and check.

Fix disconnect race crash.

---

README.md
include/FurbleUI.h
include/lv_conf.h
src/FurbleUI.cpp

* remove 'Back' in connect menu
* fix transmit power menu
* increase font size
* attempt to make fat fingers less clumsy
* change the outline colour of all buttons (including "Back" arrow '<')
* an attempt to improve visual identification of what is under focus
* change backlight timeout selector to have more context
* outline colour also changed to match buttons

Address UI issues in 3.0.0-rc2

---

README.md
include/FurbleUI.h
src/FurbleUI.cpp

On PWR button double-click, lock or unlock the screen. This is implemented as a modal message box that just blocks all touch input.

Add screen lock mechanism for touch screens (M5 Core2).

---

README.md
include/FurbleGPS.h
include/FurbleSettings.h
include/FurbleUI.h
src/FurbleGPS.cpp
src/FurbleSettings.cpp
src/FurbleUI.cpp

Add a setting for the GPS unit baud rate, defaults to 9600 (the old EOL) unit.
The new (v1.1) unit runs at 115200.
Also, add the GPS time age to the 'GPS Data' output. Update the GPS service interval to 50ms, to support the faster unit (may need to convert this to a FreeRTOS task/queue).
Whilst here, refactor a bit of GPS handling.

Add support for v1.1 GPS unit.

---

include/lv_conf.h

Rather than increase the font size, increase the DPI. This creates larger UI elements that are easier to access.

Tweak M5Core2 UI parameters.

---

lib/furble/CanonEOS.cpp
lib/furble/CanonEOS.h
lib/furble/FauxNY.h
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h

Move most of the UUIDs into the per-camera namespace and reduce the identifier names.
Change to the hex-parts NimBLEUUID constructor, no need to parse strings here.

Namespace refactor and NimBLEUUID cleanup.

---

include/FurbleUI.h
src/FurbleUI.cpp

Provide a simple 'LOCKED' label to indicate shutter lock status.

Add lock text to shutter page.

---

src/FurbleGPS.cpp
src/FurbleSettings.cpp

Migration to IDF means we need to manually initialize the NVS ourselves. Otherwise, we can't save anything ...

Initialise NVS.

---

.clang-format
include/FurbleUI.h
include/lv_conf.h
src/FurbleSettings.cpp
src/FurbleUI.cpp

For M5StickC:
* move right button to match physical button location
* move the 'Back' button up by a pixel, it was ever so slightly off
For M5Stack Core:
* change the DPI for M5Stack Core so the main menu doesn't need scrolling
Lighten the navigation button colour by 50% to distinguish from menu selection (otherwise it's just a solid blob of colour on overlap).

Adjust UI for devices with physical buttons

---

include/FurbleUI.h
src/FurbleUI.cpp

When entering shutter control mode, the input device configuration is completely changed.
Thus, when the disconnect dialog appears, all menu control is lost.
This adds context and controls for setting the correct input device mode when the 'Connecting' dialog appears, regardless of the current menu state.

Fix connect cancel when disconnected in shutter mode.

---

src/FurbleUI.cpp

On the M5StickC Plus displays, the intervalometer rollers were not being properly handled on boot.

Fix infinite count intervalometer boot crash.

---

README.md
lib/furble/Camera.h
lib/furble/CameraList.cpp
lib/furble/CanonEOS.cpp
lib/furble/Device.cpp
lib/furble/Device.h
lib/furble/Fujifilm.cpp
lib/furble/Fujifilm.h
lib/furble/Nikon.h
lib/furble/Sony.cpp
lib/furble/Sony.h
platformio.ini

Initial pairing/bonding and re-connection working. Shutter and focus working.
Location service data working, UTC offset hardcoded to zero. Update README with Sony support.
Refactor Fujifilm advertisement handling for consistency.
Update NimBLE-Arduino to 2.3.0.

Support for Sony ZV-1F.

---

include/FurbleControl.h
lib/furble/FujifilmSecure.cpp
lib/furble/Scan.cpp
lib/furble/Scan.h
src/FurbleControl.cpp
src/FurbleUI.cpp

During a failed reconnect, the cancel request was effectively ignored. Correct this.

Fix reconnect cancel handling.
